select * from insert_user('Ivan','Halych');
select * from insert_note(gen_random_uuid(),'aaa','bbb',(select id from users  limit  1));
select * from insert_user('John','Smit');
select * from insert_note(gen_random_uuid(),'ccc','ddd',(select id from users  limit  1 offset  1));
select * from insert_user('Ann','Merry');
select * from insert_note(gen_random_uuid(),'qqq','www',(select id from users  limit  1 offset  2));
select * from insert_note(gen_random_uuid(),'eee','ttt',(select id from users  limit  1 offset  2));
select * from insert_note(gen_random_uuid(),'hhh','jjj',(select id from users  limit  1 offset  2));
select * from select_note((select id from notes  limit 1));
select * from select_note((select id from notes  limit 1 offset 1));
select * from select_note((select id from notes  limit 1 offset 2));
select * from select_user_notes((select id from users  limit  1));
select * from select_user_notes((select id from users  limit  1 offset 1));
select * from select_user_notes((select id from users  limit  1 offset 2));
select * from select_users_notes_count();
select * from update_note_mark_deleted((select id from notes  limit 1));
select * from select_users_notes_count();
select * from update_note_mark_deleted((select id from notes  limit 1 offset 3));
select * from select_users_notes_count();
